//
//  FMStickersCaptureView.h
//
//  Created by Maurizio Cremaschi on 9/8/12.
//  Copyright (c) 2012 Flubber Media Ltd. All rights reserved.
//

#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import <CoreImage/CoreImage.h>
#import <ImageIO/ImageIO.h>

/** FMStickerCaptureView is a subclass of UIView used to display the video feed 
 coming from the camera of iPhone and iPad and overlay images that use points 
 generated by the Face Detection API available from iOS 5 onwards.
 It can be setup both in Interface Builder or programmatically in code and the
 video is automatically scaled to fit the view.
 
 The view is initialised by the startCapture method. Face Detection can be
 paused and resumed programmatically with pauseFaceDetection and
 resumeFaceDetection methods.
 
 There are also two convenience methods to handle the camera. Calling
 switchCamera: will perform a transition between the front and back facing
 camera. The shutter button should call the takePicture: method which on
 completion returns the final UIImage with the sticker attached or a NSError if
 something went wrong.
 
 Images applied to the preview and the final picture should be set on the
 sticker property.
 
 */

@class FMSticker;

@interface FMStickerCaptureView : UIView <AVCaptureVideoDataOutputSampleBufferDelegate>

/**-----------------------------------------------------------------------------
 * @name Public properties
 *  ----------------------------------------------------------------------------
 */

/** The FMSticker object currently used.
 
 This property defines the current FMSticker object used by the preview view and
 that will be attached to the final image.
 */

@property (strong, nonatomic) FMSticker *sticker;

/** A flag to activate a flash-like effect on the preview view.
 
 Setting this value to YES will trigger a fade-to-white animation of the
 preview view every time a picture is taken.
 */

@property (assign, nonatomic) BOOL showFlash;

/**-----------------------------------------------------------------------------
 * @name Initializing a capture session
 *  ----------------------------------------------------------------------------
 */

/** Sets the license string for the authorised bundle ID.
 
 The FMStickerEngine framework is a paid component. You can try it for free in
 development by using the bundle ID and the license provided in this project.
 
 In order to publish your app on the App Store, you need to purchase a valid
 license and set this property accordingly.
 
 @param license The license NSString
 */

+ (void)setLicense:(NSString *)license;

/** Returns the current license string
 
 */

+ (NSString *)license;

/** Starts the capture session and initialise all the required components.
 
 This method should be called when ready to show the preview view.
 */

- (void)startCapture;

/**-----------------------------------------------------------------------------
 * @name Manage face detection
 *  ----------------------------------------------------------------------------
 */

/** Pause the face detection.
 
 @see resumeFaceDetection
 */

- (void)pauseFaceDetection;

/** Resume the face detection.
 
 @see pauseFaceDetection
 */

- (void)resumeFaceDetection;

/**-----------------------------------------------------------------------------
 * @name Manage camera
 *  ----------------------------------------------------------------------------
 */

/** Switch between the front and back facing camera.
 @param completion A block which is called when the camera switch is completed.
 */

- (void)switchCamera:(void (^)(void))completion;

/** Takes the picture from the camera and starts the image manipulation process.
 @param completion A block which is called when the detection process is 
 completed. It returns an UIImage.
 */

- (void)takePicture:(void (^)(UIImage *picture, NSError *error))completion;

/**-----------------------------------------------------------------------------
 * @name Apply stickers to an image
 *  ----------------------------------------------------------------------------
 */

/** Takes the picture and starts the image manipulation process.
 @param image A UIImage on which the sticker will be applied. You should supply 
 an image with the correct orientation.
 @param completion A block which is called when the detection process is 
 completed. It returns an UIImage.
 */

- (void)processPicture:(UIImage *)image completion:(void (^)(UIImage *picture, NSError *error))completion;

@end
